# Generated by Django 2.0 on 2020-09-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200925_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_num',
            new_name='ReadNum',
        ),
    ]
